# Generated by Django 5.2.6 on 2025-09-29 02:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_profile_profileimage'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='profileimage',
            name='unique_primary_image_per_profile',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='age',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='display_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='tagline',
        ),
        migrations.RemoveField(
            model_name='profileimage',
            name='visibility',
        ),
        migrations.AddField(
            model_name='profile',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='children',
            field=models.CharField(choices=[('prefer_not', 'Prefer not to say'), ('yes', 'Yes'), ('none', 'None')], default='prefer_not', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='headline',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='profile',
            name='looking_for',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('bisexual', 'Bi-sexual'), ('unspecified', 'Prefer not to say')], default='unspecified', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='must_have_tags',
            field=models.CharField(blank=True, max_length=600),
        ),
        migrations.AddField(
            model_name='profile',
            name='my_gender',
            field=models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('nonbinary', 'Non-binary'), ('unspecified', 'Prefer not to say')], default='unspecified', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='my_interests',
            field=models.CharField(blank=True, max_length=600),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_age_max',
            field=models.PositiveSmallIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_age_min',
            field=models.PositiveSmallIntegerField(default=18),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_distance',
            field=models.CharField(choices=[('any', 'Any'), ('5', '5 km'), ('10', '10 km'), ('25', '25 km'), ('50', '50 km'), ('100', '100 km'), ('country', 'Countrywide')], default='any', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_intent',
            field=models.CharField(choices=[('any', 'Any'), ('friends', 'New friends'), ('casual', 'Casual dating'), ('longterm', 'Long-term'), ('marriage', 'Marriage')], default='any', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='profileimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profileimage',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='profileimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('profile',), name='one_primary_image_per_profile'),
        ),
    ]
