# Generated by Django 4.2.23 on 2025-10-15 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_privateaccessrequest_expires_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='thread',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AddField(
            model_name='thread',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
