# Generated by Django 4.2.23 on 2025-10-13 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_submitted_for_approval',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='needs_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='pending_changes',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
