# Generated by Django 4.2.23 on 2025-10-13 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_profile_last_submitted_for_approval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='diet',
            field=models.CharField(default='prefer_not', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='drinking',
            field=models.CharField(default='prefer_not', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='exercise',
            field=models.CharField(default='prefer_not', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='pets',
            field=models.CharField(default='prefer_not', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='smoking',
            field=models.CharField(default='prefer_not', max_length=20),
        ),
    ]
