# Generated by Django 4.2.23 on 2025-10-13 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_profile_diet_profile_drinking_profile_exercise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='diet',
            field=models.CharField(blank=True, default='prefer_not', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='drinking',
            field=models.CharField(blank=True, default='prefer_not', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='exercise',
            field=models.CharField(blank=True, default='prefer_not', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pets',
            field=models.CharField(blank=True, default='prefer_not', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='smoking',
            field=models.CharField(blank=True, default='prefer_not', max_length=20),
        ),
    ]
