# Generated by Django 4.2.23 on 2025-10-15 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_privateaccessrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='privateaccessrequest',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
