# Generated by Django 4.2.23 on 2025-10-16 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0014_alter_message_options_alter_thread_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('activity', models.CharField(max_length=50)),
                ('vibe', models.CharField(max_length=50)),
                ('budget', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=20)),
                ('date_time', models.DateTimeField()),
                ('area', models.CharField(max_length=100)),
                ('group_size', models.CharField(choices=[('1_on_1', '1 on 1'), ('small_group', 'Small group (3–4)'), ('group', 'Group (5+)')], default='1_on_1', max_length=20)),
                ('audience', models.CharField(choices=[('anyone', 'Anyone'), ('women_only', 'Women only'), ('men_only', 'Men only')], default='anyone', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_hotdates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_time'],
            },
        ),
        migrations.CreateModel(
            name='HotDateView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('hot_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='pages.hotdate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewed_hotdates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'hot_date')},
            },
        ),
        migrations.CreateModel(
            name='HotDateParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('hot_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='pages.hotdate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joined_hotdates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('hot_date', 'user')},
            },
        ),
    ]
