# Generated by Django 4.2.23 on 2025-10-18 05:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0015_hotdate_hotdateview_hotdateparticipant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='thread',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='hotdateparticipant',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='privateaccessrequest',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='hotdate',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='like',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='hotdate',
            name='activity',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='hotdate',
            name='audience',
            field=models.CharField(choices=[('everyone', 'Everyone'), ('males', 'Males Only'), ('females', 'Females Only')], default='everyone', max_length=20),
        ),
        migrations.AlterField(
            model_name='hotdate',
            name='budget',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hotdate',
            name='duration',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hotdate',
            name='group_size',
            field=models.CharField(choices=[('1on1', '1-on-1'), ('small', 'Small Group (2-4)'), ('medium', 'Medium Group (5-8)'), ('large', 'Large Group (9+)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='hotdate',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='hotdate',
            name='vibe',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hotdateparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hotdateview',
            name='hot_date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.hotdate'),
        ),
        migrations.AlterField(
            model_name='hotdateview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='hotdateparticipant',
            unique_together={('user', 'hot_date')},
        ),
        migrations.CreateModel(
            name='HotDateNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('cancelled', 'Cancelled'), ('updated', 'Updated'), ('reminder', 'Reminder')], max_length=20)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('hot_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.hotdate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotdate_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
