# Generated by Django 4.2.23 on 2025-10-18 05:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0016_alter_message_options_alter_thread_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hotdateparticipant',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='hotdate',
            name='cancelled_at',
        ),
        migrations.AlterField(
            model_name='hotdate',
            name='activity',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='hotdate',
            name='audience',
            field=models.CharField(choices=[('anyone', 'Anyone'), ('women_only', 'Women only'), ('men_only', 'Men only')], default='anyone', max_length=20),
        ),
        migrations.AlterField(
            model_name='hotdate',
            name='budget',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='hotdate',
            name='duration',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='hotdate',
            name='group_size',
            field=models.CharField(choices=[('1_on_1', '1 on 1'), ('small_group', 'Small group (3–4)'), ('group', 'Group (5+)')], default='1_on_1', max_length=20),
        ),
        migrations.AlterField(
            model_name='hotdate',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='hotdate',
            name='vibe',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='hotdateparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joined_hotdates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hotdateview',
            name='hot_date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='pages.hotdate'),
        ),
        migrations.AlterField(
            model_name='hotdateview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewed_hotdates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='hotdateparticipant',
            unique_together={('hot_date', 'user')},
        ),
    ]
