# Generated by Django 4.2.23 on 2025-10-18 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_thread_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thread',
            options={'ordering': ['-updated_at']},
        ),
    ]
